### ISSUE TITLE
App Name Length and Character Validation

### ISSUE THREAD

**Issue by nzoschke** [convox/kernel#110]
The API should validate that app names don't have whitespace or special characters.

App names need to match docker tag constraints:

```
RUNNING: docker tag -f kukxgeolnb wrk/worker1
time="2015-08-15T19:27:10Z" level="fatal" msg="Invalid namespace name (wrk), only [a-z0-9_] are allowed, size between 4 and 30"
```

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Oy3z9Bd6&#x2F;114-app-name-validation"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> app name validation</a>
