### ISSUE TITLE
Invalid characters in database password

### ISSUE THREAD

**Issue by mattmanning** [convox/kernel#112]
RDS database passwords are being generated with characters that need to be escaped in bash, confusing some users. We should make passwords alphanumeric.

From juan in public chat:
setting the environment variable on the command line with single quotes was no problem.  the output from "convox services info pginstalike" had characters like ` and { in the URL which need to be URI escaped before pasting them into the environment variable.   i think heroku escaped them by default when outputting the url

**Comment by nzoschke** [comment]
Fixed in https://github.com/convox/kernel/commit/25349cc621a75789a1d2788ba3a3838f401951fb
