### ISSUE TITLE
App Process Task Definition naming scheme

### ISSUE THREAD

**Issue by nzoschke** [convox/kernel#116]
On Slack, whatupdave reported seeing an extra process in an app

```
› convox ps --app slacker
ID            PROCESS  RELEASE      MEM    COMMAND
b6177f5e7f59  main     RONQXRCNSMR  256    bin/start
3bf85fb508ca  main     RMKCWIGRFKI  256    bin/start

2.2.0 in slacker/ on master
› convox ps --app slacker-agents
ID            PROCESS  RELEASE      MEM    COMMAND
3bf85fb508ca  main     RMKCWIGRFKI  256    bin/start
```

This is happening because the task definitions for these two apps are named:

* slacker-main
* slacker-agents-main

And `convox ps --app slacker` is finding `slacker-*` task definitions. We need a better strategy to name and select task definitions for a single app.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YbUHOMeb&#x2F;124-list-processes-catching-too-much"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> List processes catching too much</a>
