### ISSUE TITLE
Build Record Improvements

### ISSUE THREAD

**Issue by nzoschke** [convox/kernel#128]
We observed the following kernel log:

kernel: ns=kernel cn=build at=ExecuteLocal state=error step=build.execute app="signals-docker-empty" build="BNZTGNQFBJE" error="ValidationException: Item size has exceeded the maximum allowed size\n\tstatus code: 400, request id: []"

* Build.Save() throws an error on too large of attributes. Can we handle better than truncating?
* Build.Fail() can trigger an error but it's not propagated

**Comment by mattmanning** [comment]
Tried using extra DynamoDB columns for extended logs, but didn't get it working. My hypothesis is that the PutItem POST is still too large and timing out, but I'm not sure.

**Comment by ddollar** [comment]
Fixed
