### ISSUE TITLE
Convox API unavailable while scaling down rack

### ISSUE THREAD

**Issue by jtmarmon** [convox/kernel#135]
when rack is scaled to 2, 2 processes (one on each instance)

client: 20150826204636
server: 20150826204631

`convox rack scale --count 1`

after a little (before the scaling is complete)

```
jtmarmon$ convox rack scale
ERROR: Get https://convox-[omitted].us-east-1.elb.amazonaws.com/system: EOF
```

it works slightly into the updating and after. there's just a brief window where none of the convox services are available

**Comment by ddollar** [comment]
Solved in #154
