### ISSUE TITLE
Simple discovery API

### ISSUE THREAD

**Issue by imbriaco** [convox/kernel#157]
It would be great if the kernel exposed a simple API call to return the private IP and host:container port mappings for an app. This is particularly useful when you're running internal applications that will only be accessed by applications within the VPC and don't have an ELB attached.

Maybe something similar to the AWS metadata service to make it easy for clients to consume without authentication.

**Comment by ddollar** [comment]
Started documenting/normalizing the API in this branch: https://github.com/convox/kernel/blob/api-normalization/docs/api.yml

**Comment by ddollar** [comment]
https://github.com/convox/kernel/blob/master/docs/api.yml#L583-L584
