### ISSUE TITLE
Will you have the ability to tag the build and deploys with docker tags (feature request)

### ISSUE THREAD

**Issue by grandmore** [convox/kernel#162]
Can tags be added to the cli so they appear in deploy, build,and info etc. It's very difficult to know which build is which, especially when we start rolling back.

## Display example
**Current display**

ID | CREATED | STATUS
------------ | ------------- | -------------
RPQXMFAQLVL | 1 day ago | active
RYPZKUHXVHT | 2 day ago |
RBFTTSYHHGY | 3 day ago |

**Preferred Display**

ID | CREATED | STATUS | TAGS
------------ | ------------- | ------------- | -------------
RPQXMFAQLVL | 1 day ago | active | V3, Production, latest
RYPZKUHXVHT | 2 day ago |        | V2, Production  
RBFTTSYHHGY | 3 day ago |        | V1, Production  

#### Normal Workflow
1. Push code to github (push v2)
2. Github Webhook tells Convox to deploys new release (deploy v2)
3. Rinse and repeat

#### Rollback process
1. Push code to github (push v2)
2. github webhook tells Convox to deploy new release (deploy v2)
3. Release has problems, so I manually roll it back. (roll back deploy to v1)
4. push fixed code to github (push v3)
5. github webhook tells Convox to deploys new release (deploy v3)

This way I can manually pull back a release, but still automatically deployed a new version when it gets push to the repository again.

Currently I have no way of knowing what version is running. copying docker tags would make this trivial.

## Complex Workflow example
Our workflow is actually a little more complicated as we use 2 branches, Master and Production, with feature builds, fixes and releases within them.

Master, is for live public releases.
Production, is for internal releases.

We use the git branching model. so we have a lot of control. But it makes it doubly hard to know which release is which
![Gitflow](http://nvie.com/img/git-model@2x.png)
[A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by mattmanning** [comment]
Closing in favor of https://github.com/convox/rack/issues/193
