### ISSUE TITLE
Don't require kernel login for uninstall

### ISSUE THREAD

**Issue by mattmanning** [convox/kernel#93]
Perhaps the kernel hostname can be passed instead.

**Comment by rjocoleman** [comment]
I think this might be related? https://github.com/convox/cli/pull/55

As best I can tell the only reason login is required to uninstall is: https://github.com/convox/cli/blob/master/convox/install.go#L210 ?

**Comment by nzoschke** [comment]
moved to https://github.com/convox/cli/issues/64
