### ISSUE TITLE
Specify `docker-compose.yml` file for deployment

### ISSUE THREAD

**Issue by bradgessler** [convox/kernel#97]
Its more convenient for my development workflow to have `docker-compose.yml` as my development environment. When its time to deploy to production, I'd prefer to run a command like `convox deploy -f production.yml` and have my application build from that file.

Since this breaks convention with other developers on my team (e.g. they need to know to type in `convox deploy -f production.yml`) it would also be useful if a `.convox/deploy-config` file is written into my repo and checked-in. This configuration would be read by convox to know where the deployment file is located.

**Comment by nzoschke** [comment]
+1 for a `-f file.yml` for `convox start` and `convox deploy` to offer more options and parity with `docker-compose`.

I understand the reasoning for the `deploy-config` file but we want to avoid adding convox-specific config files.  What if your use case was supported by having `convox start` check for and use a `development.yml` if present?

**Comment by bradgessler** [comment]
I think you'll run into people with different opinions on how they structure their `docker-compose.yml` files between production and development environments. Some people will use `docker-compose.yml` for development and have a `production.yml` file. Others will use `docker-compose.yml` for production and have a `development.yml` file. There are good reasons for each of these approaches.

A convox config file could look like:

```
local:
  docker_compose_path: docker-compose.yml
deploy:
  docker_compose_path: production.yml
```
Another approach, if you don't want your own config file, is to use the `labels` in Docker Compose YML. That could look something like this:

```
app:
  image: acme/my-app
  labels:
    convox.target: deploy
db:
  image: mysql
  labels:
    convox.target: local
```

There is something to be said about convox working right out of the box for some of the simpler example projects you've published, but when it comes to more non-trivial applications or workflows, its nice to have more control over what services get deployed.

I'm sure a common use case would be deploying a rails app to AWS. In production people will want to use RDS. It would be great if the `db` service could be aliased to the RDS host via some directive, label, or configuration, but at the very least it should be possible to not deploy that service.

**Comment by gjohnson** [comment]
The labels approach sounds interesting to me. I'd be worried about `-f` in larger teams where someone might choose the wrong one when collaborating on a project.

**Comment by nzoschke** [comment]
Using docker-compose labels sounds looks like a nice design to me too.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;MXDqUXxi&#x2F;169-specify-docker-compose-yml-file-for-start-and-build"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Specify docker-compose.yml file for start and build</a>

**Comment by martnu** [comment]
If anyone is reading this after getting:
```
ERROR: unknown flag: -f
```
The new flag is:
```
--manifest (-m)
```
